<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="4" failures="1" disabled="0" errors="0" timestamp="2017-02-06T13:25:16" time="120.284" name="AllTests">
  <testsuite name="LinearSolver" tests="1" failures="0" disabled="0" errors="0" time="0.052">
    <testcase name="HandlesLinearSolver" status="run" time="0.052" classname="LinearSolver" />
  </testsuite>
  <testsuite name="ResidualComputation" tests="1" failures="0" disabled="0" errors="0" time="0">
    <testcase name="HandlesResidualComputation" status="run" time="0" classname="ResidualComputation" />
  </testsuite>
  <testsuite name="ChecksPeriodicGrid" tests="1" failures="0" disabled="0" errors="0" time="0.133">
    <testcase name="HandlesPeridicGrid" status="run" time="0.133" classname="ChecksPeriodicGrid" />
  </testsuite>
  <testsuite name="SquareCavityG84" tests="1" failures="1" disabled="0" errors="0" time="120.098">
    <testcase name="SquareCavityG84" status="run" time="120.098" classname="SquareCavityG84">
      <failure message="unknown file&#x0A;Unknown C++ exception thrown in the test body." type=""><![CDATA[unknown file
Unknown C++ exception thrown in the test body.]]></failure>
    </testcase>
  </testsuite>
</testsuites>
